Traceback (most recent call last):
  File "O:\Envs\nycudopcs\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "O:\Envs\nycudopcs\Lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jaen8\AppData\Local\Programs\Python\Python311\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "O:\Envs\nycudopcs\Lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# import module "nycudopcs2023"
import nycudopcs2023

# call function in "nycudopcs2023"
nycudopcs2023.youfool()

# call variables in "nycudopcs2023"
print(nycudopcs2023.student_id)

# call another function in "nycudopcs2023"
for i in range(3):
    nycudopcs2023.gossip(idx=i)


------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 2[0m
[0;32m      1[0m [38;5;66;03m# import module "nycudopcs2023"[39;00m
[1;32m----> 2[0m [38;5;28;01mimport[39;00m [38;5;21;01mnycudopcs2023[39;00m
[0;32m      4[0m [38;5;66;03m# call function in "nycudopcs2023"[39;00m
[0;32m      5[0m nycudopcs2023[38;5;241m.[39myoufool()

[1;31mModuleNotFoundError[0m: No module named 'nycudopcs2023'

